### PR TITLE
Add support for Heltec ESP32 based boards

### PR DESCRIPTION
**Pull request by lokkju**
This pull request adds documentation, code, and pre-built static libs for Heltec ESP32 based boards

### CODE REVIEW

**Comment by kent-williams** [comment]
Hi @lokkju, thank you for your contribution!

The only part left to do is to re-build the library sources for m0 & m0+, since they will be effected by the header changes as well. 

Thanks!
-Kent

**Comment by lokkju** [comment]
Probably a good idea; though since the header changes are name-only, and don't change the internal enum values, I'm pretty sure the existing libs are still compatible.  That said, it's probably best for you to rebuild all the binaries yourself.

**Comment by kent-williams** [comment]
@lokkju This currently breaks support for the cortex-m0 targets without a rebuild of the library. I am happy to rebuild the libs for the m0's. Would you mind giving me push permission to your fork so I can PR on top of your branch. 

Thanks!
-Kent

**Comment by lokkju** [comment]
@kent-williams you should already have access to my branch; "allow edits from maintainers" is enabled for this pull request.

**Comment by kent-williams** [comment]
@lokkju Even easier, thanks!

**Pull request merged**
