### PR TITLE
Renamed ST HAL Conflicts

### PR DESCRIPTION
**Pull request by kent-williams**
- Renamed duplicate struct def and pin name.
- Removed duplicate assert_param, not currently used.

### CODE REVIEW

**Comment by kent-williams** [comment]
More conflicts incoming soon...

**Comment by lthiery** [comment]
Ha okay. Not sure if you were intending on this being WIP, but tag it as WIP when you know it is

**Comment by kent-williams** [comment]
Yeah sorry about that, I wasn't intending it to be a WIP, but I discovered more conflicts with the Catena libraries.

**Comment by kent-williams** [comment]
This is ready to be merged now.

Using Catena as working example now, as Discovery board requires manually setting SPI pins, because SPI1 is not used by default. Will switch back when longfi-device is updated to take SPI reference from user.

**Pull request merged**
