### PR TITLE
Arduino Library Fixes

### PR DESCRIPTION
**Pull request by kent-williams**
This PR brings the library closer to the official Arduino library guidelines. 

- [x] Moved example in readme to example folder so it can be selected in the arduino IDE.

- [x] Added library properties file, which is required if library source files are not in top directory.

- [x] Removed lingering git files from longfi-device.

- [ ] This repo should be rename to LongFi to follow the standard naming style, which is to match the name of the library. I realize this isn't ideal with our repo naming norms, but this will eliminate a lot of people using the library incorrectly. We could also name it ArduinoLongFi to make it a little more clear when looking at our list of longfi related repos, but that would require renaming the library files and classes/funcs.

### CODE REVIEW

**Comment by lthiery** [comment]
> This repo should be rename to LongFi to follow the standard naming style

I would like to avoid calling it LongFi as a repo because then it will be assumed to be the example implementation. I think it's important to specify Arduino in the library name.

**Comment by madninja** [comment]
@lthiery much agreed. Especially since we’ll likely end up having implementations for other platforms.

**Comment by lthiery** [comment]
@madninja we already do :) 
[longfi in RTFM](https://github.com/helium/longfi-device-rs/tree/master/examples/stm32l0x2)

**Comment by kent-williams** [comment]
Ok, just tested cloning right into Arduino/libraries and it works fine as is.

**Comment by madninja** [comment]
Nice.. so what’s the naming convention? I see longfi-device-rs and longfi-arduino
Maybe pick one and stick with it?

**Comment by lthiery** [comment]
Well, I guess I was going for conciseness when possible. `longfi-arduino` is obviously for a device IMO, so I omitted device. But we could throw it in I guess :man_shrugging:

**Comment by madninja** [comment]
I’m fine with concise.. if so would longfi-device-rs be renamed?

**Comment by lthiery** [comment]
I didn't want to do `longfi-rs` because there's potentially `longfi-hotspot-rs`; to that point, I have a module in concentrate called longfi-hotspot that could eventually be its own crate.

Basically, my thinking is `arduino` implies device but `rs` could be hotspot or device.

**Comment by madninja** [comment]
🤷‍♀ I prefer consistent naming but it’s no big deal if you want to mix platforms and languages

**Pull request merged**
